LICOGI_10_REVOLUTION/Controllers/AdminController.cs
using LICOGI_10_REVOLUTION.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace LICOGI_10_REVOLUTION.Controllers
{
    public class AdminController : Controller
    {
        [LoginFilter]
        public ActionResult Solution(int? id)
        {
            // From id = 7, is child menu of Solution id = 6
            // 6,7,8,9,10 -> introduce page

            SolutionModel model = new SolutionModel {ListPageModel = new List<PageModel>()};
            if (id == null)
            {
                id = 6;
            }
            using (LOGICO_10_REVOLUTIONEntities context = new LOGICO_10_REVOLUTIONEntities())
            {
                if (id != 6)
                {
                    model.ListPageModel.Add(context.TB_FIX_PAGE_CONTENT.Where(x => x.Id == id)
                     .Select(x => new PageModel
                     {
                         Id = x.Id,
                         Name = x.Name,
                         ContentText = x.ContentText,
                         ContentTextEn = x.ContentTextEn
                     }).FirstOrDefault());
                }
                else
                {
                    model.ListPageModel.AddRange(context.TB_FIX_PAGE_CONTENT.Where(x => x.Id == 6)
                                        .Select(x => new PageModel
                                        {
                                            Id = x.Id,
                                            Name = x.Name,
                                            ContentText = x.ContentText,
                                            ContentTextEn = x.ContentTextEn
                                        }).ToList());

                    model.ListPageModel.AddRange(context.TB_INTRODUCE.Select(x => new PageModel
                    {
                        Id = x.Id,
                        Name = x.Name,
                        ContentText = x.ContentText,
                        ContentTextEn = x.ContentTextEn
                    }).ToList());
                }

                model.listPage = context.TB_FIX_PAGE_CONTENT.Select(x => new PageModel
                {
                    Id = x.Id,
                    Name = x.Name
                }).ToList();
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateSolution(PageModel model)
        {
            int result = 0;
            using (LOGICO_10_REVOLUTIONEntities context = new LOGICO_10_REVOLUTIONEntities())
            {
                var page = context.TB_FIX_PAGE_CONTENT.FirstOrDefault(x => x.Id == model.Id);

                if (page != null)
                {
                    page.ContentText = model.ContentText;
                    page.ContentTextEn = model.ContentTextEn;

                    context.TB_FIX_PAGE_CONTENT.Attach(page);
                    var entry = context.Entry(page);

                    entry.Property(x => x.ContentText).IsModified = true;
                    entry.Property(x => x.ContentTextEn).IsModified = true;

                    result = context.SaveChanges();
                }
            }

            if (result == 0)
            {
            }

            return RedirectToAction("Solution", new { model.Id });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateSolutionIntroduce(List<PageModel> listPageModel)
        {
            int result;
            using (LOGICO_10_REVOLUTIONEntities context = new LOGICO_10_REVOLUTIONEntities())
            {
                // remove first null page listPageModel -> 0,1,2,3,4,5
                listPageModel.RemoveAt(0);
                // 0,1,2,34
                var pages = context.TB_INTRODUCE.ToList();

                for (int i = 0; i < 5; i++)
                {
                    pages[i].ContentText = listPageModel[i].ContentText;
                    pages[i].ContentTextEn = listPageModel[i].ContentTextEn;

                    context.TB_INTRODUCE.Attach(pages[i]);
                    var entry = context.Entry(pages[i]);

                    entry.Property(x => x.ContentText).IsModified = true;
                    entry.Property(x => x.ContentTextEn).IsModified = true;

                    context.SaveChanges();
                }

                result = 5;
            }

            if (result == 0)
            {
            }

            return RedirectToAction("Solution", new { Id = 6 });
        }

        [LoginFilter]
        public ActionResult Project()
        {
            ICollection<TB_ARTICAL> listArtical;

            using (LOGICO_10_REVOLUTIONEntities context = new LOGICO_10_REVOLUTIONEntities())
            {
                listArtical = context.TB_ARTICAL
                    .Where(x => x.ArticalType == Constant.ARTICAL_PROJECT)
                    .OrderByDescending(x => x.CreateDate)
                    .ToList();
            }

            return View(listArtical);
        }

        [LoginFilter]
        public ActionResult News()
        {
            ICollection<TB_ARTICAL> listArtical;

            using (LOGICO_10_REVOLUTIONEntities context = new LOGICO_10_REVOLUTIONEntities())
            {
                listArtical = context.TB_ARTICAL
                    .Where(x => x.ArticalType == Constant.ARTICAL_NEWS || x.ArticalType == Constant.ARTICAL_YOUTH)
                    .OrderByDescending(x => x.CreateDate)
                    .ToList();
            }

            return View(listArtical);
        }

        [LoginFilter]
        public ActionResult NewArticalView(byte articalType)
        {
            ArticalModel model = new ArticalModel
            {
                ArticalType = articalType,
                ListArticalType = GetArticalTypeDropDown(),
                ListSolutionType = GetSolutionTypeDropDown(),
                IsActive = true
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult NewArtical(ArticalModel model)
        {
            int result;
            byte articalType = model.ArticalType;

            if (model.ArticalType != 1)
            {
                ModelState.Remove("SolutionType");
            }

            if (!ModelState.IsValid)
            {
                model.ListArticalType = GetArticalTypeDropDown();
                model.ListSolutionType = GetSolutionTypeDropDown();
                return View("NewArticalView", model);
            }

            using (LOGICO_10_REVOLUTIONEntities context = new LOGICO_10_REVOLUTIONEntities())
            {
                var artical = new TB_ARTICAL
                {
                    Title = model.Title,
                    TitleEn = model.TitleEn,
                    ArticalType = model.ArticalType,
                    SolutionType = model.SolutionType,
                    AvataUrl = model.AvataUrl.Replace(@"/Images/", @"/ImageThumbs/"),
                    Description = model.Description,
                    DescriptionEn = model.DescriptionEn,
                    FriendlyUrl = model.FriendlyUrl,
                    FriendlyUrlEn = model.FriendlyUrlEn,
                    DisplayOrder = model.DisplayOrder,
                    IsProjectDone = model.IsProjectDone,
                    IsActive = model.IsActive,
                    ContentText = model.ContentText,
                    ContentTextEn = model.ContentTextEn,
                    CreateDate = DateTime.Now
                };

                context.TB_ARTICAL.Add(artical);
                result = context.SaveChanges();
            }

            if (result == 0)
            {
                model.ListArticalType = GetArticalTypeDropDown();
                model.ListSolutionType = GetSolutionTypeDropDown();
                TempData["MESSAGE"] = "Hệ thống gặp vấn đề, xin thử lại sau";
                return View("NewArticalView", model);
            }

            TempData["MESSAGE"] = "Thêm thành công";
            if (articalType == 1)
            {
                return RedirectToAction("Project");
            }
            else if (articalType == 2)
            {
                return RedirectToAction("News");
            }
            else
            {
                return RedirectToAction("News");
            }
        }

        [LoginFilter]
        public ActionResult EditArticalView(int id)
        {
            ArticalModel model;

            using (LOGICO_10_REVOLUTIONEntities context = new LOGICO_10_REVOLUTIONEntities())
            {
                model = context.TB_ARTICAL
                    .Where(x => x.Id == id)
                    .Select(x => new ArticalModel
                    {
                        Id = x.Id,
                        ArticalType = x.ArticalType,
                        SolutionType = x.SolutionType,
                        Title = x.Title,
                        TitleEn = x.TitleEn,
                        AvataUrl = x.AvataUrl,
                        Description = x.Description,
                        DescriptionEn = x.DescriptionEn,
                        ContentText = x.ContentText,
                        ContentTextEn = x.ContentTextEn,
                        FriendlyUrl = x.FriendlyUrl,
                        FriendlyUrlEn = x.FriendlyUrlEn,
                        DisplayOrder = x.DisplayOrder,
                        IsProjectDone = x.IsProjectDone.Value,
                        IsActive = x.IsActive
                    }).FirstOrDefault();
            }
            if (model != null)
            {
                model.ListArticalType = GetArticalTypeDropDown();
                model.ListSolutionType = GetSolutionTypeDropDown();
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditArtical(ArticalModel model)
        {
            int result;

LICOGI_10_REVOLUTION/Controllers/FileController.cs
using LICOGI_10_REVOLUTION.Models;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LICOGI_10_REVOLUTION.Controllers
{
    public class FileController : Controller
    {
        //
        // GET: /File/

        public ActionResult Manager()
        {
            ICollection<TB_FILE> listFile = new List<TB_FILE>();
            using (LOGICO_10_REVOLUTIONEntities context = new LOGICO_10_REVOLUTIONEntities())
            {
                listFile = context.TB_FILE.OrderByDescending(x => x.UploadDate).ToList();
            }
            return View(listFile);
        }

        public ActionResult Gallery()
        {
            ICollection<TB_FILE> top10Files = new List<TB_FILE>();
            using (LOGICO_10_REVOLUTIONEntities context = new LOGICO_10_REVOLUTIONEntities())
            {
                top10Files = context.TB_FILE.OrderByDescending(x => x.UploadDate).Take(10).ToList();
            }
            return View(top10Files);
        }

        [HttpPost]
        public ActionResult Upload(IEnumerable<HttpPostedFileBase> listFile, string type)
        {
            int result = 0;
            string imagePath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Uploads/Images/");
            string imageThumbPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Uploads/ImageThumbs/");
            string filePath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Uploads/Files/");

            List<TB_FILE> listToDB = new List<TB_FILE>();

            foreach (var item in listFile)
            {
                TB_FILE file = new TB_FILE();
                if (item.ContentType.Contains("image"))
                {
                    var image = Image.FromStream(item.InputStream);
                    var thumbFile = image.GetThumbnailImage(200, 200, () => false, IntPtr.Zero);

                    // Save File
                    image.Save(imagePath + item.FileName);
                    thumbFile.Save(imageThumbPath + item.FileName);

                    file.Url = @"Uploads/Images/" + item.FileName;
                    file.ThumbUrl = @"Uploads/ImageThumbs/" + item.FileName;
                }
                else
                {
                    // Save File
                    item.SaveAs(filePath + item.FileName);

                    file.Url = @"Uploads/Files/" + item.FileName;
                }
                file.Name = item.FileName;
                file.FileType = item.ContentType;
                file.UploadDate = DateTime.Now;
                listToDB.Add(file);
            }

            using (LOGICO_10_REVOLUTIONEntities context = new LOGICO_10_REVOLUTIONEntities())
            {
                foreach (var item in listToDB)
                {
                    if (!context.TB_FILE.Any(x => x.Name.Equals(item.Name) && x.Url.Equals(item.Url)))
                    {
                        context.TB_FILE.Add(item);
                    }
                }
                result = context.SaveChanges();
            }

            if (result != 0)
            {
                string viewName = type.Equals("1") ? "_ListFileManagerPartial" : "_ListFilePartial";
                return PartialView(viewName, listToDB);
            }

            return Json(Constant.REQUEST_FAIL, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Search(string input, string type)
        {
            ICollection<TB_FILE> listResult = new List<TB_FILE>();
            using (LOGICO_10_REVOLUTIONEntities context = new LOGICO_10_REVOLUTIONEntities())
            {
                if (!string.IsNullOrEmpty(input))
                {
                    listResult = context.TB_FILE.Where(x => x.Name.Contains(input)).OrderByDescending(x => x.UploadDate).ToList();
                }
                else
                {
                    listResult = context.TB_FILE.OrderByDescending(x => x.UploadDate).Take(10).ToList();
                }
            }

            string viewName = type.Equals("1") ? "_ListFileManagerPartial" : "_ListFilePartial";
            return PartialView(viewName, listResult);
        }

        public ActionResult Delete(int id)
        {
            using (LOGICO_10_REVOLUTIONEntities context = new LOGICO_10_REVOLUTIONEntities())
            {
                if (!context.TB_FILE.Any(x => x.Id == id))
                {
                    Response.Write(Constant.REQUEST_FAIL);
                    return null;
                }

                var deleteItem = context.TB_FILE.Where(x => x.Id == id).FirstOrDefault();

                if (deleteItem != null)
                {
                    // Delete file on hard disk
                    string fileUri = AppDomain.CurrentDomain.BaseDirectory + "/" + deleteItem.Url;
                    if (System.IO.File.Exists(fileUri))
                    {
                        System.IO.File.Delete(fileUri);
                    }

                    if (deleteItem.FileType.Contains("image"))
                    {
                        string fileUriThumb = AppDomain.CurrentDomain.BaseDirectory + "/" + deleteItem.ThumbUrl;

                        if (System.IO.File.Exists(fileUriThumb))
                        {
                            System.IO.File.Delete(fileUriThumb);
                        }
                    }

                    // Delete info in database
                    context.TB_FILE.Remove(deleteItem);
                }

                context.SaveChanges();
            }

            Response.Write(Constant.REQUEST_SUCCESS);
            return null;
        }
    }
}

LICOGI_10_REVOLUTION/Views/Admin/EditArticalView.cshtml
@model LICOGI_10_REVOLUTION.Models.ArticalModel
@{
    ViewBag.Title = "EditArtical";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@section style {
    <style>
        #page-wrapper label {
            margin-top: 8px;
        }

        #page-wrapper .row {
            margin-top: 15px;
        }
    </style>
}
<!-- /.navbar-top-links -->
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            <li>
                <a href="index.html"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
            </li>
            <li>
                <a href="index.html"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
            </li>
        </ul>
    </div>
    <!-- /.sidebar-collapse -->
</div>

<div id="page-wrapper">
    <div class="col-md-8 no-padding">
        <div class="row">
            <h2>Cập nhật nội dung dự án</h2>
        </div>
        @using (Html.BeginForm("EditArtical", "Admin", FormMethod.Post))
        {
            <div class="row">
                @if (TempData["MESSAGE"] != null)
                {
                    <label class="text-danger text-center" style="width:100%">@TempData["MESSAGE"]</label>

                }
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            </div>
            @Html.AntiForgeryToken()
            @Html.HiddenFor(m => m.Id)
            <div class="row">
                <label class="col-md-3 no-padding">Tên bài viết</label>
                <div class="col-md-5">
                    @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Title, "", new { @class = "text-danger" })
                </div>
            </div>

    <div class="row">
        <label class="col-md-3 no-padding">Tên bài viết tiếng anh</label>
        <div class="col-md-5">
            @Html.TextBoxFor(m => m.TitleEn, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.TitleEn, "", new { @class = "text-danger" })
        </div>
    </div>

            <div class="row">
                <label class="col-md-3 no-padding">Loại bài viết</label>
                <div class="col-md-3">
                    @Html.DropDownListFor(m => m.ArticalType, Model.ListArticalType, "Lựa Chọn", new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.ArticalType, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="row">
                <label class="col-md-3 no-padding">Loại dự án</label>
                <div class="col-md-3">
                    @Html.DropDownListFor(m => m.SolutionType, Model.ListSolutionType, "Lựa Chọn", new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.SolutionType, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="row">
                <label class="col-md-3 no-padding">Ảnh đại diện</label>
                <div class="col-md-5">
                    @Html.TextBoxFor(m => m.AvataUrl, new { @class = "form-control", placeholder = "Nhập đường dẫn ảnh" })
                    @Html.ValidationMessageFor(m => m.AvataUrl, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="row">
                <label class="col-md-3 no-padding">Mô tả ngắn</label>
                <div class="col-md-5">
                    @Html.TextAreaFor(m => m.Description, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" })
                </div>
            </div>

    <div class="row">
        <label class="col-md-3 no-padding">Mô tả ngắn tiếng anh</label>
        <div class="col-md-5">
            @Html.TextAreaFor(m => m.DescriptionEn, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.DescriptionEn, "", new { @class = "text-danger" })
        </div>
    </div>

            <div class="row">
                <label class="col-md-3 no-padding">Đường dẫn</label>
                <div class="col-md-5">
                    @Html.TextBoxFor(m => m.FriendlyUrl, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.FriendlyUrl, "", new { @class = "text-danger" })
                </div>
            </div>

    <div class="row">
        <label class="col-md-3 no-padding">Đường dẫn tiếng anh</label>
        <div class="col-md-5">
            @Html.TextBoxFor(m => m.FriendlyUrlEn, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.FriendlyUrlEn, "", new { @class = "text-danger" })
        </div>
    </div>

            <div class="row">
                <label class="col-md-3 no-padding">Thứ tự hiển thị</label>
                <div class="col-md-5">
                    @Html.TextBoxFor(m => m.DisplayOrder, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.DisplayOrder, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="row">
                <div class="col-md-2 project-done" style="width:45px">
                    @Html.CheckBoxFor(m => m.IsProjectDone, new { @class = "form-control" })
                </div>
                <label for="IsProjectDone" class="col-md-3 no-padding project-done">Hoàn Thành</label>

                <div class="col-md-2" style="width:45px">
                    @Html.CheckBoxFor(m => m.IsActive, new { @class = "form-control" })
                </div>
                <label for="IsActive" class="col-md-3 no-padding">Hiển thị</label>
            </div>

            <div class="row">
                <label>Nội Dung</label>
            </div>

            <div class="row">
                @Html.TextAreaFor(m => m.ContentText, 100, 100, new { @class = "form-control html-content" })
            </div>
    <br /><br />
    <div class="row">
        <label>Nội dung tiếng anh</label>
    </div>

    <div class="row">
        @Html.TextAreaFor(m => m.ContentTextEn, 100, 100, new { @class = "form-control html-content" })
    </div>
            <br />
            <div class="row text-right">
                <button type="submit" class="btn btn-primary">Lưu</button>
            </div>
        }
        <br /><br /><br /><br /><br /><br /><br /><br />
    </div>

<div class="col-md-4" id="gallery">
    @{Html.RenderAction("Gallery", "File", null);}
</div>
</div>

@section scripts{
    <script src="~/Scripts/tinymce/js/tinymce/tinymce.min.js"></script>
    <script>
        tinymce.init({
            selector: '.html-content',  // change this value according to your HTML
            height: 500,
            plugins: [
              'advlist autolink lists link image charmap print preview anchor',
              'searchreplace visualblocks code fullscreen',
              'insertdatetime media table contextmenu paste code'
            ],
            toolbar: 'undo redo | insert | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
            content_css: '//www.tinymce.com/css/codepen.min.css',
            convert_urls: false,
        });
    </script>
<script>
        var upLoadUrl = '@Url.Action("Upload", "File")';
        var searchUrl = '@Url.Action("Search", "File")';
</script>
<script src="~/Scripts/my/file-gallery.js"></script>
}

LICOGI_10_REVOLUTION/Views/Admin/EditMachineView.cshtml
@model LICOGI_10_REVOLUTION.Models.MachineModel
@{
    ViewBag.Title = "Thay đổi Bị Thi Công";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@section style {
    <style>
        #page-wrapper label {
            margin-top: 8px;
        }

        #page-wrapper .row {
            margin-top: 15px;
        }
    </style>
}
<!-- /.navbar-top-links -->
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            <li>
                <a href="index.html"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
            </li>
            <li>
                <a href="index.html"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
            </li>
        </ul>
    </div>
    <!-- /.sidebar-collapse -->
</div>

<div id="page-wrapper">
    <div class="col-md-8 no-padding">
        <div class="row">
            <h2>Thêm bài</h2>
        </div>
        @using (Html.BeginForm("EditMachine", "Admin", FormMethod.Post))
        {
            <div class="row">
                @if (TempData["MESSAGE"] != null)
                {
                    <label class="text-danger text-center" style="width:100%">@TempData["MESSAGE"]</label>

                }
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            </div>
            @Html.AntiForgeryToken()
            @Html.HiddenFor(m => m.Id)
            <div class="row">
                <label class="col-md-3 no-padding">Tên thiết bị</label>
                <div class="col-md-5">
                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="row">
                <label class="col-md-3 no-padding">Tên thiết bị tiếng anh</label>
                <div class="col-md-5">
                    @Html.TextBoxFor(m => m.NameEn, new { @class = "form-control" })
                </div>
            </div>

            <div class="row">
                <label class="col-md-3 no-padding">Hình Ảnh</label>
                <div class="col-md-5">
                    @Html.TextBoxFor(m => m.ImageUrl, new { @class = "form-control", placeholder = "Nhập đường dẫn ảnh" })
                    @Html.ValidationMessageFor(m => m.ImageUrl, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="row">
                <label class="col-md-3 no-padding">Số Lượng</label>
                <div class="col-md-5">
                    @Html.TextAreaFor(m => m.Count, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Count, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="row">
                <label class="col-md-3 no-padding">Năm sản xuất</label>
                <div class="col-md-5">
                    @Html.TextAreaFor(m => m.Year, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Year, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="row">
                <label class="col-md-3 no-padding">Nơi sản xuất</label>
                <div class="col-md-5">
                    @Html.TextBoxFor(m => m.MadeIn, new { @class = "form-control" })
                </div>
            </div>

            <div class="row">
                <label class="col-md-3 no-padding">Nơi sản xuất tiếng anh</label>
                <div class="col-md-5">
                    @Html.TextBoxFor(m => m.MadeInEn, new { @class = "form-control" })
                </div>
            </div>

            <div class="row">
                <label class="col-md-3 no-padding">Công suất</label>
                <div class="col-md-5">
                    @Html.TextBoxFor(m => m.Power, new { @class = "form-control" })
                </div>
            </div>

            <div class="row">
                <label class="col-md-3 no-padding">Công suất tiếng anh</label>
                <div class="col-md-5">
                    @Html.TextBoxFor(m => m.PowerEn, new { @class = "form-control" })
                </div>
            </div>

            <div class="row">
                <label>Thông số kĩ thuật</label>
            </div>

            <div class="row">
                @Html.TextAreaFor(m => m.DetailInfo, 100, 100, new { @class = "form-control html-content" })
            </div>
            <br /><br />
            <div class="row">
                <label>Thông số kĩ thuật tiếng anh</label>
            </div>

            <div class="row">
                @Html.TextAreaFor(m => m.DetailInfoEn, 100, 100, new { @class = "form-control html-content" })
            </div>
            <br />
            <div class="row text-right">
                <button type="submit" class="btn btn-primary">Lưu</button>
            </div>
        }
        <br /><br /><br /><br /><br /><br /><br /><br />
    </div>

    <div class="col-md-4" id="gallery">
        @{Html.RenderAction("Gallery", "File", null);}
    </div>
</div>

@section scripts{
    <script src="~/Scripts/tinymce/js/tinymce/tinymce.min.js"></script>
    <script>
        tinymce.init({
            selector: '.html-content',  // change this value according to your HTML
            height: 500,
            theme: 'modern',
            plugins: ['advlist autolink lists link image charmap print preview hr anchor pagebreak',
            'searchreplace wordcount visualblocks visualchars code fullscreen',
            'insertdatetime media nonbreaking save table contextmenu directionality',
            'emoticons template paste textcolor colorpicker textpattern imagetools'
            ],
            toolbar1: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
            toolbar2: 'print preview media | forecolor backcolor emoticons',
            content_css: '//www.tinymce.com/css/codepen.min.css',
            convert_urls: false,
        });
    </script>

    <script>
        var upLoadUrl = '@Url.Action("Upload", "File")';
        var searchUrl = '@Url.Action("Search", "File")';
    </script>
    <script src="~/Scripts/my/file-gallery.js"></script>
}

LICOGI_10_REVOLUTION/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<!-- /.navbar-top-links -->
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            <li>
                <a href="index.html"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
            </li>
            <li>
                <a href="index.html"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
            </li>
            <li>
                <a href="index.html"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
            </li>
        </ul>
    </div>
    <!-- /.sidebar-collapse -->
</div>

<div id="page-wrapper">


</div>
<!-- /.navbar-static-side -->